### ISSUE TITLE
Doesnt Work With Pygame_gui  0.5.7

### ISSUE THREAD

**Issue by spfaul** [MyreMylar/network_chat#1]
im trying to study this project but it doesnt work with the latest version of pygame, could you update it?

**Comment by MyreMylar** [comment]
Thanks for the reminder!

I just went through and updated it. It's not a very complete chat program - just the very basics, but it _should_ function now. I had it running on a LAN a couple of times in the past.

Don't forget to manually set the IP in `network_chat.py` to whatever comes up when you press `Start Server`, otherwise it won't work.

**Comment by spfaul** [comment]
Thanks for updating it! It works now!
